
name: Spell Check
on: [push, pull_request]

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install cspell
        run: npm install -g cspell

      - name: Spell Check
        run: cspell "ASPNETCore10/**/*.cs" "ASPNETCore10/**/*.md" "ASPNETCore10/**/*.json" "ASPNETCore10/**/*.yml" "ASPNETCore10/**/*.cshtml"--no-progress --show-suggestions